[server]
port = 80
cookieSecret = "dontforgottochangeme"
enableXsrfProtection = false
enableCORS = true

[theme]
primaryColor = "#FFFFFF"
backgroundColor = "#000000"
secondaryBackgroundColor = "#1A1A1A"
textColor = "#FFFFFF"
font = "sans serif"