
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chromadb
      - ./CV:/app/CV

  frontend:
    # image: trev8989/rag_cv-frontend:latest
    build: 
      context: .
      dockerfile: Frontend/Dockerfile
    container_name: frontend
    env_file:
      - .env
    ports:
      - "80:8o"
    volumes:
      - ./CV:/app/CV
volumes:
  chroma_data: